import type { ComponentType } from "react";
import * as Pages from "./index";

export interface RouteConfig {
  path: string;
  component: ComponentType<any>;
  protected?: boolean;
  layout?: "replit" | "none";
  redirectTo?: string;
}

export const placeholderRoutes = [
];

export const publicRoutes: RouteConfig[] = [
  { path: "/login", component: Pages.Login },
  { path: "/register", component: Pages.Register },
  { path: "/forgot-password", component: Pages.ForgotPassword },
  { path: "/reset-password", component: Pages.ResetPassword },
  { path: "/verify-email", component: Pages.VerifyEmail },
  { path: "/runtime-test", component: Pages.RuntimePublicPage },
  { path: "/", component: Pages.Landing },
  { path: "/pricing", component: Pages.Pricing },
  { path: "/features", component: Pages.Features },
  { path: "/about", component: Pages.About },
  { path: "/careers", component: Pages.Careers },
  { path: "/blog", component: Pages.Blog },
  { path: "/blog/:slug", component: Pages.BlogDetail },
  { path: "/docs", component: Pages.Docs },
  { path: "/contact-sales", component: Pages.ContactSales },
  { path: "/terms", component: Pages.Terms },
  { path: "/privacy", component: Pages.Privacy },
  { path: "/dpa", component: Pages.DPA },
  { path: "/commercial-agreement", component: Pages.CommercialAgreement },
  { path: "/report-abuse", component: Pages.ReportAbuse },
  { path: "/status", component: Pages.Status },
  { path: "/forum", component: Pages.Forum },
  { path: "/compare/:slug", component: Pages.ComparePage },
  { path: "/marketing/bounties", component: Pages.MarketingBounties },
  { path: "/marketing/deployments", component: Pages.PublicDeploymentsPage },
  { path: "/marketing/teams", component: Pages.PublicTeamPage },
  { path: "/compare", component: Pages.Compare },
  { path: "/compare/github-codespaces", component: Pages.VsGitHubCodespaces },
  { path: "/compare/glitch", component: Pages.VsGlitch },
  { path: "/compare/heroku", component: Pages.VsHeroku },
  { path: "/compare/codesandbox", component: Pages.VsCodeSandbox },
  { path: "/compare/aws-cloud9", component: Pages.VsAwsCloud9 },
  { path: "/solutions/app-builder", component: Pages.AppBuilder },
  { path: "/solutions/website-builder", component: Pages.WebsiteBuilder },
  { path: "/solutions/game-builder", component: Pages.GameBuilder },
  { path: "/solutions/dashboard-builder", component: Pages.DashboardBuilder },
  { path: "/solutions/chatbot-builder", component: Pages.ChatbotBuilder },
  { path: "/solutions/internal-ai-builder", component: Pages.InternalAIBuilder },
  { path: "/solutions/enterprise", component: Pages.Enterprise },
  { path: "/solutions/startups", component: Pages.Startups },
  { path: "/solutions/freelancers", component: Pages.Freelancers },
  { path: "/tutorials", component: Pages.Tutorials },
  { path: "/changelog", component: Pages.Changelog },
  { path: "/case-studies", component: Pages.CaseStudies },
  { path: "/help-center", component: Pages.HelpCenter },
  { path: "/contact", component: Pages.Contact },
  { path: "/accessibility", component: Pages.Accessibility },
  { path: "/mobile", component: Pages.MobileMarketingPage },
  { path: "/mobile-workspace/:projectId", component: Pages.MobileWorkspace },
  { path: "/ai", component: Pages.AI },
  { path: "/ai-documentation", component: Pages.AIDocumentation },
  { path: "/mcp", component: Pages.MCPInterface },
  { path: "/polyglot", component: Pages.PolyglotBackendPage },
  { path: "/demo", component: Pages.AuthenticationDemo },
  { path: "/theme-validation", component: Pages.ThemeValidation },
  { path: "/press", component: Pages.Press },
  { path: "/partners", component: Pages.Partners },
  { path: "/security", component: Pages.Security },
  { path: "/desktop", component: Pages.Desktop },
  { path: "/subprocessors", component: Pages.Subprocessors },
  { path: "/student-dpa", component: Pages.StudentDPA },
  { path: "/languages", component: Pages.Languages },
  { path: "/templates/languages", component: Pages.Languages },
  { path: "/team", component: Pages.PublicTeamPage },
  { path: "/collaboration", component: Pages.PublicTeamPage },
  { path: "/deployments", component: Pages.PublicDeploymentsPage },
  { path: "/newsletter-confirmed", component: Pages.NewsletterConfirmed },
  { path: "/newsletter/confirm", component: Pages.NewsletterConfirm },
  { path: "/newsletter/unsubscribe", component: Pages.NewsletterUnsubscribe },
  { path: "/share/:shareId", component: Pages.SharedSnippet },
  { path: "/u/:username/:projectname", component: Pages.ProjectPage, layout: "replit" },
  { path: "/u/:username", component: Pages.UserProfile, layout: "replit" },
  { path: "/ide/new", component: Pages.Dashboard, layout: "replit" },
  { path: "/ide/:id", component: Pages.IDEPage },
  { path: "/marketplace", component: Pages.Marketplace, layout: "replit" },
  { path: "/marketplace/templates", component: Pages.TemplateMarketplace, layout: "replit" },
  { path: "/templates", component: Pages.TemplatesPage, layout: "replit" },
  { path: "/community", component: Pages.Community, layout: "replit" },
  { path: "/community/post/:id", component: Pages.CommunityPost, layout: "replit" },
  { path: "/search", component: Pages.SearchPage, layout: "replit" },
  { path: "/explore", component: Pages.Explore, layout: "replit" },
];

export const protectedRoutes: RouteConfig[] = [
  { path: "/ai-agent/studio", component: Pages.AIAgentStudio, layout: "replit" },
  { path: "/github-import", component: Pages.GitHubImport, layout: "replit" },
  { path: "/projects/:id/import/figma", component: Pages.FigmaImport, layout: "replit" },
  { path: "/projects/:id/import/bolt", component: Pages.BoltImport, layout: "replit" },
  { path: "/projects/:id/import/lovable", component: Pages.LovableImport, layout: "replit" },
  { path: "/new", component: Pages.Dashboard, layout: "replit" },
  { path: "/editor/new", component: Pages.Dashboard, layout: "replit" },
  { path: "/projects/new", component: Pages.Dashboard, layout: "replit" },
  { path: "/dashboard", component: Pages.Dashboard, layout: "replit" },
  { path: "/agent-activity", component: Pages.AgentActivity, layout: "replit" },
  { path: "/apps", component: Pages.Apps, layout: "replit" },
  { path: "/teams", component: Pages.Teams, layout: "replit" },
  { path: "/teams/new", component: Pages.NewTeamPage, layout: "replit" },
  { path: "/teams/:id", component: Pages.TeamPage, layout: "replit" },
  { path: "/teams/:id/settings", component: Pages.TeamSettings, layout: "replit" },
  { path: "/vnc", component: Pages.VNCPage, layout: "replit" },
  { path: "/notifications", component: Pages.Notifications, layout: "replit" },
  { path: "/analytics", component: Pages.Analytics, layout: "replit" },
  { path: "/scalability", component: Pages.Scalability, layout: "replit" },
  { path: "/education", component: Pages.Education, layout: "replit" },
  { path: "/api-sdk", component: Pages.APISDKPage, layout: "replit" },
  { path: "/mobile-apps", component: Pages.MobileAppsPage, layout: "replit" },
  { path: "/advanced/mobile", component: Pages.MobileAdmin, layout: "replit" },
  { path: "/advanced/sso", component: Pages.SSOConfiguration, layout: "replit" },
  { path: "/advanced/collaboration", component: Pages.Community, layout: "replit" },
  { path: "/advanced/storage", component: Pages.Usage, layout: "replit" },
  { path: "/advanced/community", component: Pages.Community, layout: "replit" },
  { path: "/settings", component: Pages.Settings, layout: "replit" },
  { path: "/settings/notifications", component: Pages.Notifications, layout: "replit" },
  { path: "/settings/billing", component: Pages.Usage, layout: "replit" },
  { path: "/profile/:username?", component: Pages.Profile, layout: "replit" },
  { path: "/home", component: Pages.Home, layout: "replit" },
  { path: "/projects", component: Pages.ProjectsPage, layout: "replit" },
  { path: "/projects/:id", component: Pages.ProjectPage, layout: "replit" },
  { path: "/project/:id", component: Pages.ProjectPage, layout: "replit" },
  { path: "/editor/:id", component: Pages.EditorRedirect },
  { path: "/runtimes", component: Pages.RuntimesPage, layout: "replit" },
  { path: "/runtime-diagnostics", component: Pages.RuntimeDiagnosticsPage, layout: "replit" },
  { path: "/user/:username", component: Pages.UserProfile, layout: "replit" },
  { path: "/user/settings", component: Pages.UserSettings, layout: "replit" },
  { path: "/search-advanced", component: Pages.SearchPage, layout: "replit" },
  { path: "/secrets", component: Pages.Secrets, layout: "replit" },
  { path: "/workflows", component: Pages.Workflows, layout: "replit" },
  { path: "/ssh", component: Pages.SSH, layout: "replit" },
  { path: "/security-scanner", component: Pages.SecurityScanner, layout: "replit" },
  { path: "/dependencies", component: Pages.Dependencies, layout: "replit" },
  { path: "/object-storage", component: Pages.ObjectStorage, layout: "replit" },
  { path: "/projects/:id/database", component: Pages.DatabaseManagement },
  { path: "/projects/:id/secrets", component: Pages.SecretManagement },
  { path: "/usage-alerts", component: Pages.UsageAlerts },
  { path: "/projects/:id/preview", component: Pages.PreviewWithDevTools },
  { path: "/mobile-admin", component: Pages.MobileAdmin, layout: "replit" },
  { path: "/admin", component: Pages.AdminDashboard, layout: "replit" },
  { path: "/admin/dashboard", component: Pages.AdminDashboard, layout: "replit" },
  { path: "/admin/usage", component: Pages.AdminUsage, layout: "replit" },
  { path: "/admin/ai-usage", component: Pages.AdminAIUsage, layout: "replit" },
  { path: "/admin/requests", component: Pages.AdminFormRequests, layout: "replit" },
  { path: "/admin/billing", component: Pages.AdminBilling, layout: "replit" },
  { path: "/admin/ai-models", component: Pages.AdminAIModels, layout: "replit" },
  { path: "/admin/ai-optimization", component: Pages.AdminAIOptimization, layout: "replit" },
  { path: "/admin/seo", component: Pages.AdminSEOManagement, layout: "replit" },
  { path: "/admin/monitoring", component: Pages.AdminMonitoring, layout: "replit" },
  { path: "/admin/system-monitoring", component: Pages.AdminSystemMonitoring, layout: "replit" },
  { path: "/admin/pitch-deck", component: Pages.PitchDeck, layout: "replit" },
  { path: "/admin/chatgpt", component: Pages.ChatGPTAdmin },
  { path: "/admin/users", component: Pages.AdminUsers, layout: "replit" },
  { path: "/admin/projects", component: Pages.AdminProjects, layout: "replit" },
  { path: "/admin/subscriptions", component: Pages.AdminSubscriptions, layout: "replit" },
  { path: "/admin/activity", component: Pages.AdminActivityLogs, layout: "replit" },
  { path: "/admin/settings", component: Pages.AdminSettings, layout: "replit" },
  { path: "/admin/api-keys", component: Pages.AdminApiKeys, layout: "replit" },
  { path: "/admin/support", component: Pages.AdminSupport, layout: "replit" },
  { path: "/admin/cms", component: Pages.AdminCMS, layout: "replit" },
  { path: "/admin/docs", component: Pages.AdminDocs, layout: "replit" },
  { path: "/account", component: Pages.Account, layout: "replit" },
  { path: "/deployments", component: Pages.Deployments, layout: "replit" },
  { path: "/usage", component: Pages.Usage, layout: "replit" },
  { path: "/billing", component: Pages.Billing, layout: "replit" },
  { path: "/cycles", component: Pages.Cycles, layout: "replit" },
  { path: "/bounties", component: Pages.Bounties, layout: "replit" },
  { path: "/powerups", component: Pages.PowerUps, layout: "replit" },
  { path: "/badges", component: Pages.Badges, layout: "replit" },
  { path: "/subscribe", component: Pages.Subscribe, layout: "replit" },
  { path: "/plans", component: Pages.Plans, layout: "replit" },
  { path: "/learn", component: Pages.Learn, layout: "replit" },
  { path: "/support", component: Pages.Support, layout: "replit" },
  { path: "/themes", component: Pages.Themes, layout: "replit" },
  { path: "/health", component: Pages.HealthDashboard, layout: "replit" },
  { path: "/performance", component: Pages.PerformanceDashboard, layout: "replit" },
  { path: "/sso-configuration", component: Pages.SSOConfiguration, layout: "replit" },
  { path: "/audit-logs", component: Pages.AuditLogs, layout: "replit" },
  { path: "/custom-roles", component: Pages.CustomRoles, layout: "replit" },
  { path: "/assistant", component: Pages.AssistantPage, layout: "replit" },
  { path: "/code-search", component: Pages.CodeSearchPage, layout: "replit" },
  { path: "/problems", component: Pages.ProblemsPage, layout: "replit" },
  { path: "/database", component: Pages.DatabasePage, layout: "replit" },
  { path: "/console", component: Pages.ConsolePage, layout: "replit" },
  { path: "/shell", component: Pages.ShellPage, layout: "replit" },
  { path: "/packages", component: Pages.PackagesPage, layout: "replit" },
  { path: "/kv-store", component: Pages.KVStorePage, layout: "replit" },
  { path: "/preview", component: Pages.PreviewPage, layout: "replit" },
  { path: "/authentication", component: Pages.AuthenticationPage, layout: "replit" },
  { path: "/extensions", component: Pages.ExtensionsPage, layout: "replit" },
  { path: "/integrations", component: Pages.IntegrationsPage, layout: "replit" },
  { path: "/networking", component: Pages.NetworkingPage, layout: "replit" },
  { path: "/threads", component: Pages.ThreadsPage, layout: "replit" },
  { path: "/referrals", component: Pages.ReferralsPage, layout: "replit" },
];

export interface SolarTechAppConfig {
  path: string;
  projectName: string;
  projectDescription: string;
  projectId: number;
  component: ComponentType<any>;
}

export const solarTechApps: SolarTechAppConfig[] = [
  {
    path: "/u/admin/solartech-ai-chat",
    projectName: "SolarTech AI Chat",
    projectDescription: "Professional solar technology AI assistant",
    projectId: 1001,
    component: Pages.SolarTechAIChatApp,
  },
  {
    path: "/u/admin/solartech-crm",
    projectName: "SolarTech CRM",
    projectDescription: "Solar business customer relationship management",
    projectId: 1002,
    component: Pages.SolarTechCRMApp,
  },
  {
    path: "/u/admin/solartech-fortune500-store",
    projectName: "Fortune500 Solar Store",
    projectDescription: "E-commerce platform for solar technology products",
    projectId: 1003,
    component: Pages.SolarTechStoreApp,
  },
  {
    path: "/solartech-ai-chat",
    projectName: "SolarTech AI Chat",
    projectDescription: "Professional solar technology AI assistant",
    projectId: 1001,
    component: Pages.SolarTechAIChatApp,
  },
  {
    path: "/solartech-crm",
    projectName: "SolarTech CRM",
    projectDescription: "Solar business customer relationship management",
    projectId: 1002,
    component: Pages.SolarTechCRMApp,
  },
  {
    path: "/salesforcepro-crm",
    projectName: "SolarTech CRM",
    projectDescription: "Solar business customer relationship management",
    projectId: 1002,
    component: Pages.SolarTechCRMApp,
  },
  {
    path: "/solartech-fortune500-store",
    projectName: "Fortune500 Solar Store",
    projectDescription: "E-commerce platform for solar technology products",
    projectId: 1003,
    component: Pages.SolarTechStoreApp,
  },
];

export { Pages };
