export type RealtimeEventType =
  | "message:new"
  | "message:edit"
  | "message:delete"
  | "message:seen"
  | "message:delivered"
  | "typing:start"
  | "typing:stop"
  | "presence:update"
  | "presence:bulk"
  | "conversation:created"
  | "conversation:updated"
  | "conversation:archived"
  | "conversation:restored"
  | "conversation:participant:added"
  | "conversation:participant:removed"
  | "notification:new"
  | "notification:read"
  | "notification:readAll"
  | "system:error"
  | "system:ping"
  | "system:pong";

export type WebSocketDirection = "incoming" | "outgoing";

export interface BaseRealtimeEvent<TType extends RealtimeEventType = RealtimeEventType, TPayload = unknown> {
  type: TType;
  payload: TPayload;
  /**
   * Milliseconds since Unix epoch, generated by the backend.
   * May be absent for some client-originated events until echoed by server.
   */
  timestamp?: number;
  /**
   * Unique identifier of the event, typically generated by backend.
   * Optional for client-emitted events before server ack.
   */
  eventId?: string;
  /**
   * Direction of the event relative to the client.
   * Not part of the raw wire protocol — used internally in the client.
   */
  __direction__?: WebSocketDirection;
}

// Message-related payloads

export interface RealtimeMessageBase {
  id: string;
  conversationId: string;
  senderId: string;
  content: string;
  createdAt: string;
  updatedAt?: string;
  isEdited?: boolean;
  replyToMessageId?: string | null;
  /**
   * Optional metadata such as attachments, reactions, custom flags, etc.
   */
  metadata?: Record<string, unknown>;
}

export interface RealtimeNewMessagePayload extends RealtimeMessageBase {}

export interface RealtimeEditMessagePayload {
  id: string;
  conversationId: string;
  content: string;
  updatedAt: string;
  isEdited: true;
  /**
   * Optional metadata changes applied along with the edit.
   */
  metadata?: Record<string, unknown>;
}

export interface RealtimeDeleteMessagePayload {
  id: string;
  conversationId: string;
  deletedAt: string;
  /**
   * Optional: indicates if the delete was for everyone or only for the user.
   */
  scope?: "everyone" | "self";
}

export interface RealtimeMessageSeenPayload {
  messageId: string;
  conversationId: string;
  userId: string;
  seenAt: string;
}

export interface RealtimeMessageDeliveredPayload {
  messageId: string;
  conversationId: string;
  userId: string;
  deliveredAt: string;
}

// Typing payloads

export interface RealtimeTypingStartPayload {
  conversationId: string;
  userId: string;
  startedAt: string;
}

export interface RealtimeTypingStopPayload {
  conversationId: string;
  userId: string;
  stoppedAt: string;
  /**
   * Optional: message that was sent after typing ended, if any.
   */
  messageId?: string;
}

// Presence payloads

export type PresenceStatus = "online" | "offline" | "away" | "busy";

export interface RealtimePresenceUpdatePayload {
  userId: string;
  status: PresenceStatus;
  lastActiveAt: string | null;
  /**
   * Optional client-specific context: device, platform, etc.
   */
  clientInfo?: {
    device?: string;
    platform?: string;
    userAgent?: string;
  };
}

export interface RealtimePresenceBulkPayload {
  users: RealtimePresenceUpdatePayload[];
}

// Conversation payloads

export interface RealtimeConversationParticipant {
  userId: string;
  role: "owner" | "admin" | "member" | "guest";
  joinedAt: string;
}

export interface RealtimeConversationBase {
  id: string;
  title: string | null;
  isGroup: boolean;
  createdAt: string;
  createdBy: string;
  updatedAt?: string;
  archivedAt?: string | null;
  participants: RealtimeConversationParticipant[];
  /**
   * Optional metadata for conversation-specific configuration.
   */
  metadata?: Record<string, unknown>;
}

export interface RealtimeConversationCreatedPayload extends RealtimeConversationBase {}

export interface RealtimeConversationUpdatedPayload {
  id: string;
  title?: string | null;
  updatedAt: string;
  metadata?: Record<string, unknown>;
}

export interface RealtimeConversationArchivedPayload {
  id: string;
  archivedAt: string;
}

export interface RealtimeConversationRestoredPayload {
  id: string;
  restoredAt: string;
}

export interface RealtimeConversationParticipantAddedPayload {
  conversationId: string;
  participant: RealtimeConversationParticipant;
}

export interface RealtimeConversationParticipantRemovedPayload {
  conversationId: string;
  userId: string;
  removedAt: string;
}

// Notification payloads

export interface RealtimeNotificationBase {
  id: string;
  userId: string;
  type: string;
  createdAt: string;
  readAt?: string | null;
  payload: Record<string, unknown>;
}

export interface RealtimeNotificationNewPayload extends RealtimeNotificationBase {}

export interface RealtimeNotificationReadPayload {
  id: string;
  userId: string;
  readAt: string;
}

export interface RealtimeNotificationReadAllPayload {
  userId: string;
  readAt: string;
}

// System payloads

export interface RealtimeSystemErrorPayload {
  code: string;
  message: string;
  details?: Record<string, unknown>;
  /**
   * If the error is associated with a particular event.
   */
  causedByEventId?: string;
}

export interface RealtimeSystemPingPayload {
  pingId: string;
  sentAt: string;
}

export interface RealtimeSystemPongPayload {
  pingId: string;
  sentAt: string;
  receivedAt: string;
}

// Event type mappings

export interface RealtimeEventPayloadMap {
  "message:new": RealtimeNewMessagePayload;
  "message:edit": RealtimeEditMessagePayload;
  "message:delete": RealtimeDeleteMessagePayload;
  "message:seen": RealtimeMessageSeenPayload;
  "message:delivered": RealtimeMessageDeliveredPayload;
  "typing:start": RealtimeTypingStartPayload;
  "typing:stop": RealtimeTypingStopPayload;
  "presence:update": RealtimePresenceUpdatePayload;
  "presence:bulk": RealtimePresenceBulkPayload;
  "conversation:created": RealtimeConversationCreatedPayload;
  "conversation:updated": RealtimeConversationUpdatedPayload;
  "conversation:archived": RealtimeConversationArchivedPayload;
  "conversation:restored": RealtimeConversationRestoredPayload;
  "conversation:participant:added": RealtimeConversationParticipantAddedPayload;
  "conversation:participant:removed": RealtimeConversationParticipantRemovedPayload;
  "notification:new": RealtimeNotificationNewPayload;
  "notification:read": RealtimeNotificationReadPayload;
  "notification:readAll": RealtimeNotificationReadAllPayload;
  "system:error": RealtimeSystemErrorPayload;
  "system:ping": RealtimeSystemPingPayload;
  "system:pong": RealtimeSystemPongPayload;
}

export type RealtimeEvent<TType extends RealtimeEventType = RealtimeEventType> =
  BaseRealtimeEvent<TType, RealtimeEventPayloadMap[TType]>;

// Utility types

export type AnyRealtimeEvent = RealtimeEvent<RealtimeEventType>;

export type OutgoingRealtimeEvent<TType extends RealtimeEventType = RealtimeEventType> =
  RealtimeEvent<TType> & { __direction__: "outgoing" };

export type IncomingRealtimeEvent<TType extends RealtimeEventType = RealtimeEventType> =
  RealtimeEvent<TType> & { __direction__: "incoming" };

export type RealtimeEventHandler<TType extends RealtimeEventType = RealtimeEventType> = (
  event: IncomingRealtimeEvent<TType>
) => void | Promise<void>;

// Type guards

export function isRealtimeEventType(value: unknown): value is RealtimeEventType {
  if (typeof value !== "string") return false;
  switch (value) {
    case "message:new":
    case "message:edit":
    case "message:delete":
    case "message:seen":
    case "message:delivered":
    case "typing:start":
    case "typing:stop":
    case "presence:update":
    case "presence:bulk":
    case "conversation:created":
    case "conversation:updated":
    case "conversation:archived":
    case "conversation:restored":
    case "conversation:participant:added":
    case "conversation:participant:removed":
    case "notification:new":
    case "notification:read":
    case "notification:readAll":
    case "system:error":
    case "system:ping":
    case "system:pong":
      return true;
    default:
      return false;
  }
}

export function createOutgoingEvent<TType extends RealtimeEventType>(
  type: TType,
  payload: RealtimeEventPayloadMap[TType],
  options?: { eventId?: string; timestamp?: number }
): OutgoingRealtimeEvent<TType> {
  return {
    type,
    payload,
    eventId: options?.eventId,
    timestamp