// @ts-nocheck
import { db } from './db';
import { createLogger } from './utils/logger';
// import { templates } from '@shared/schema';

const logger = createLogger('seed-templates');

const REPLIT_TEMPLATES = [
  // Web Development
  {
    slug: 'nextjs-starter',
    name: 'Next.js 14 Starter',
    description: 'Full-stack Next.js app with TypeScript, Tailwind CSS, and App Router',
    icon: 'Globe',
    category: 'web',
    tags: ['nextjs', 'react', 'typescript', 'tailwind', 'fullstack'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Next.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['App Router', 'TypeScript', 'Tailwind CSS', 'ESLint', 'SEO optimized'],
    files: {
      'package.json': JSON.stringify({
        name: 'nextjs-starter',
        dependencies: {
          'next': 'latest',
          'react': 'latest',
          'react-dom': 'latest'
        },
        devDependencies: {
          '@types/node': 'latest',
          '@types/react': 'latest',
          'typescript': 'latest',
          'tailwindcss': 'latest'
        }
      }),
      'app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js!</h1>
    </main>
  );
}`
    },
    dependencies: { 'next': '^14.0.0', 'react': '^18.0.0' },
    uses: 5420,
    stars: 342,
    forks: 89,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'html-css-js',
    name: 'HTML/CSS/JS',
    description: 'Vanilla HTML, CSS, and JavaScript starter template',
    icon: 'Code',
    category: 'web',
    tags: ['html', 'css', 'javascript', 'vanilla', 'beginner'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'None',
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Pure HTML/CSS/JS', 'No build tools', 'Instant preview'],
    files: {
      'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Website</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <h1>Hello World!</h1>
    <script src="script.js"></script>
</body>
</html>`,
      'style.css': `body {
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    margin: 0;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

h1 {
    color: white;
    font-size: 3rem;
}`,
      'script.js': `console.log('Hello from JavaScript!');`
    },
    dependencies: {},
    uses: 12340,
    stars: 567,
    forks: 234,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'astro-blog',
    name: 'Astro Blog',
    description: 'Static blog site with Astro, Markdown, and Tailwind CSS',
    icon: 'BookOpen',
    category: 'web',
    tags: ['astro', 'blog', 'markdown', 'static-site', 'tailwind'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Astro',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Markdown blog', 'Static generation', 'SEO optimized', 'Fast loading'],
    files: {},
    dependencies: { 'astro': '^4.0.0' },
    uses: 2340,
    stars: 189,
    forks: 67,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'remix-app',
    name: 'Remix Full-Stack',
    description: 'Full-stack web app with Remix, TypeScript, and Prisma',
    icon: 'Layers',
    category: 'web',
    tags: ['remix', 'fullstack', 'typescript', 'prisma', 'react'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Remix',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Server-side rendering', 'Data loading', 'TypeScript', 'Database ready'],
    files: {},
    dependencies: { '@remix-run/node': '^2.0.0', '@remix-run/react': '^2.0.0' },
    uses: 3210,
    stars: 234,
    forks: 89,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'qwik-city',
    name: 'Qwik City App',
    description: 'Resumable web app with Qwik City for instant loading',
    icon: 'Zap',
    category: 'web',
    tags: ['qwik', 'resumable', 'performance', 'typescript'],
    authorName: 'Qwik Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Qwik',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Resumable', 'Zero hydration', 'Instant loading', 'TypeScript'],
    files: {},
    dependencies: { '@builder.io/qwik': '^1.0.0', '@builder.io/qwik-city': '^1.0.0' },
    uses: 1890,
    stars: 156,
    forks: 45,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nuxt3-app',
    name: 'Nuxt 3 Universal',
    description: 'Universal Vue app with Nuxt 3, TypeScript, and auto-imports',
    icon: 'Package',
    category: 'web',
    tags: ['nuxt', 'vue', 'universal', 'typescript', 'fullstack'],
    authorName: 'Nuxt Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Nuxt',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Auto imports', 'TypeScript', 'Server rendering', 'Vue 3'],
    files: {},
    dependencies: { 'nuxt': '^3.0.0' },
    uses: 2670,
    stars: 198,
    forks: 67,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'solid-start',
    name: 'SolidStart App',
    description: 'Full-stack SolidJS app with fine-grained reactivity',
    icon: 'Cpu',
    category: 'web',
    tags: ['solid', 'solidstart', 'reactivity', 'typescript'],
    authorName: 'Solid Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'SolidJS',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Fine-grained reactivity', 'TypeScript', 'No virtual DOM', 'Fast'],
    files: {},
    dependencies: { '@solidjs/start': '^0.4.0', 'solid-js': '^1.8.0' },
    uses: 1560,
    stars: 134,
    forks: 34,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'gatsby-portfolio',
    name: 'Gatsby Portfolio',
    description: 'Portfolio site with Gatsby, GraphQL, and optimized images',
    icon: 'User',
    category: 'web',
    tags: ['gatsby', 'portfolio', 'graphql', 'react', 'static'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Gatsby',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['GraphQL', 'Image optimization', 'PWA', 'SEO'],
    files: {},
    dependencies: { 'gatsby': '^5.0.0', 'react': '^18.0.0' },
    uses: 2340,
    stars: 178,
    forks: 56,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'react-vite',
    name: 'React + Vite',
    description: 'Lightning-fast React development with Vite, TypeScript, and modern tooling',
    icon: 'Zap',
    category: 'web',
    tags: ['react', 'vite', 'typescript', 'fast-refresh'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'React',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Hot Module Replacement', 'TypeScript', 'Fast builds', 'Modern tooling'],
    files: {},
    dependencies: { 'react': '^18.0.0', 'vite': '^5.0.0' },
    uses: 3210,
    stars: 256,
    forks: 67,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'vue3-composition',
    name: 'Vue 3 + Composition API',
    description: 'Modern Vue 3 app with Composition API, TypeScript, and Pinia',
    icon: 'Code',
    category: 'web',
    tags: ['vue', 'composition-api', 'typescript', 'pinia'],
    authorName: 'Vue Masters',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Vue.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Composition API', 'TypeScript', 'Pinia store', 'Vue Router'],
    files: {},
    dependencies: { 'vue': '^3.0.0', '@vue/composition-api': 'latest' },
    uses: 2150,
    stars: 178,
    forks: 45,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'angular-universal',
    name: 'Angular Universal SSR',
    description: 'Server-side rendered Angular app with Universal and TypeScript',
    icon: 'Shield',
    category: 'web',
    tags: ['angular', 'ssr', 'typescript', 'universal'],
    authorName: 'Angular Experts',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Angular',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Server-side rendering', 'TypeScript', 'Angular CLI', 'RxJS'],
    files: {},
    dependencies: { '@angular/core': '^17.0.0' },
    uses: 1890,
    stars: 145,
    forks: 38,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'svelte-kit',
    name: 'SvelteKit Full-Stack',
    description: 'Full-stack SvelteKit app with TypeScript and Tailwind CSS',
    icon: 'Layers',
    category: 'web',
    tags: ['svelte', 'sveltekit', 'typescript', 'fullstack'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'SvelteKit',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['SvelteKit', 'TypeScript', 'Tailwind CSS', 'Full-stack'],
    files: {},
    dependencies: { '@sveltejs/kit': '^2.0.0' },
    uses: 1670,
    stars: 123,
    forks: 31,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Backend/API
  {
    slug: 'express-typescript-api',
    name: 'Express.js TypeScript API',
    description: 'Production-ready REST API with Express, TypeScript, and JWT auth',
    icon: 'Server',
    category: 'api',
    tags: ['express', 'typescript', 'api', 'jwt', 'rest'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Express.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['TypeScript', 'JWT Authentication', 'MongoDB', 'Input validation'],
    files: {},
    dependencies: { 'express': '^4.0.0', 'typescript': '^5.0.0' },
    uses: 4320,
    stars: 289,
    forks: 76,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'fastapi-python',
    name: 'FastAPI Python Backend',
    description: 'High-performance Python API with FastAPI, async support, and auto-docs',
    icon: 'Zap',
    category: 'api',
    tags: ['python', 'fastapi', 'async', 'api', 'swagger'],
    authorName: 'Python Pro',
    authorVerified: true,
    language: 'Python',
    framework: 'FastAPI',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Async/await', 'Auto documentation', 'Type hints', 'Fast performance'],
    files: {},
    dependencies: {},
    uses: 3890,
    stars: 267,
    forks: 69,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'django-rest-api',
    name: 'Django REST Framework',
    description: 'Full-featured Django REST API with authentication and PostgreSQL',
    icon: 'Database',
    category: 'api',
    tags: ['python', 'django', 'rest', 'postgresql', 'api'],
    authorName: 'Django Masters',
    authorVerified: true,
    language: 'Python',
    framework: 'Django',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Django REST Framework', 'PostgreSQL', 'JWT Auth', 'Admin panel'],
    files: {},
    dependencies: {},
    uses: 2780,
    stars: 198,
    forks: 52,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nestjs-microservices',
    name: 'NestJS Microservices',
    description: 'Scalable microservices architecture with NestJS and TypeScript',
    icon: 'GitBranch',
    category: 'api',
    tags: ['nestjs', 'microservices', 'typescript', 'scalable'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'NestJS',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Microservices', 'TypeScript', 'Message queues', 'Docker ready'],
    files: {},
    dependencies: { '@nestjs/core': '^10.0.0' },
    uses: 2340,
    stars: 176,
    forks: 43,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'graphql-apollo',
    name: 'GraphQL Apollo Server',
    description: 'GraphQL API with Apollo Server, TypeScript, and subscriptions',
    icon: 'GitGraph',
    category: 'api',
    tags: ['graphql', 'apollo', 'typescript', 'subscriptions'],
    authorName: 'GraphQL Experts',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Apollo',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['GraphQL', 'Subscriptions', 'TypeScript', 'Apollo Server'],
    files: {},
    dependencies: { 'apollo-server': '^3.0.0' },
    uses: 1980,
    stars: 143,
    forks: 36,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Mobile
  {
    slug: 'react-native-expo',
    name: 'React Native + Expo',
    description: 'Cross-platform mobile app with React Native and Expo SDK',
    icon: 'Smartphone',
    category: 'mobile',
    tags: ['react-native', 'expo', 'mobile', 'ios', 'android'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'React Native',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Expo SDK', 'Cross-platform', 'Hot reload', 'Native features'],
    files: {},
    dependencies: { 'expo': '^49.0.0', 'react-native': '^0.72.0' },
    uses: 3560,
    stars: 234,
    forks: 61,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'flutter-material',
    name: 'Flutter Material App',
    description: 'Beautiful Flutter app with Material Design and state management',
    icon: 'Palette',
    category: 'mobile',
    tags: ['flutter', 'dart', 'material-design', 'mobile'],
    authorName: 'Flutter Pro',
    authorVerified: true,
    language: 'Dart',
    framework: 'Flutter',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Material Design', 'State management', 'Hot reload', 'Cross-platform'],
    files: {},
    dependencies: {},
    uses: 2890,
    stars: 189,
    forks: 49,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'ionic-angular',
    name: 'Ionic Angular App',
    description: 'Hybrid mobile app with Ionic, Angular, and Capacitor',
    icon: 'Radio',
    category: 'mobile',
    tags: ['ionic', 'angular', 'capacitor', 'hybrid', 'mobile'],
    authorName: 'Ionic Masters',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Ionic',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Ionic components', 'Angular', 'Capacitor', 'PWA ready'],
    files: {},
    dependencies: { '@ionic/angular': '^7.0.0' },
    uses: 1670,
    stars: 112,
    forks: 28,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Games
  {
    slug: 'phaser3-platformer',
    name: 'Phaser 3 Platformer',
    description: '2D platformer game with Phaser 3, physics, and level editor',
    icon: 'Gamepad2',
    category: 'game',
    tags: ['phaser', 'game', 'javascript', 'platformer', '2d'],
    authorName: 'Game Dev Pro',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Phaser',
    difficulty: 'intermediate' as const,
    estimatedTime: '4 minutes',
    features: ['Physics engine', 'Level editor', 'Sprite animations', 'Sound effects'],
    files: {},
    dependencies: { 'phaser': '^3.0.0' },
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'unity-webgl',
    name: 'Unity WebGL Starter',
    description: '3D Unity game exported to WebGL for browser play',
    icon: 'Gamepad',
    category: 'game',
    tags: ['unity', 'webgl', '3d', 'game', 'c-sharp'],
    authorName: 'Unity Masters',
    authorVerified: true,
    language: 'C#',
    framework: 'Unity',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['3D graphics', 'WebGL export', 'Physics', 'Multiplayer ready'],
    files: {},
    dependencies: {},
    uses: 1890,
    stars: 134,
    forks: 35,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'kaboomjs-arcade',
    name: 'Kaboom.js Arcade Game',
    description: 'Retro arcade game with Kaboom.js game engine',
    icon: 'Zap',
    category: 'game',
    tags: ['kaboom', 'game', 'javascript', 'arcade', 'retro'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Kaboom.js',
    difficulty: 'beginner' as const,
    estimatedTime: '2 minutes',
    features: ['Simple API', 'Built-in physics', 'Asset loading', 'Scene management'],
    files: {},
    dependencies: { 'kaboom': 'latest' },
    uses: 1560,
    stars: 98,
    forks: 24,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Data Science & ML
  {
    slug: 'jupyter-datascience',
    name: 'Jupyter Data Science',
    description: 'Complete data science environment with Jupyter, NumPy, Pandas, and Matplotlib',
    icon: 'BarChart',
    category: 'data',
    tags: ['python', 'jupyter', 'pandas', 'numpy', 'data-science'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: 'Jupyter',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Jupyter notebook', 'Data visualization', 'Statistical analysis', 'Machine learning'],
    files: {},
    dependencies: {},
    uses: 4560,
    stars: 312,
    forks: 82,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'tensorflow-ml',
    name: 'TensorFlow ML Starter',
    description: 'Machine learning project with TensorFlow, Keras, and model training',
    icon: 'Brain',
    category: 'data',
    tags: ['python', 'tensorflow', 'machine-learning', 'keras', 'ai'],
    authorName: 'ML Experts',
    authorVerified: true,
    language: 'Python',
    framework: 'TensorFlow',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Neural networks', 'Model training', 'Data preprocessing', 'GPU support'],
    files: {},
    dependencies: {},
    uses: 3210,
    stars: 234,
    forks: 61,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'pytorch-computer-vision',
    name: 'PyTorch Computer Vision',
    description: 'Computer vision project with PyTorch, image classification, and CNNs',
    icon: 'Eye',
    category: 'data',
    tags: ['python', 'pytorch', 'computer-vision', 'cnn', 'ai'],
    authorName: 'Vision AI',
    authorVerified: true,
    language: 'Python',
    framework: 'PyTorch',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['CNN models', 'Image classification', 'Transfer learning', 'GPU acceleration'],
    files: {},
    dependencies: {},
    uses: 2670,
    stars: 189,
    forks: 49,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Bots & Automation
  {
    slug: 'discord-bot-js',
    name: 'Discord Bot JavaScript',
    description: 'Feature-rich Discord bot with slash commands and database',
    icon: 'Bot',
    category: 'bot',
    tags: ['discord', 'bot', 'javascript', 'discord.js'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Discord.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Slash commands', 'Database integration', 'Music player', 'Moderation tools'],
    files: {},
    dependencies: { 'discord.js': '^14.0.0' },
    uses: 3890,
    stars: 267,
    forks: 69,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'telegram-bot-python',
    name: 'Telegram Bot Python',
    description: 'Telegram bot with inline keyboards, webhooks, and payments',
    icon: 'MessageCircle',
    category: 'bot',
    tags: ['telegram', 'bot', 'python', 'automation'],
    authorName: 'Bot Masters',
    authorVerified: true,
    language: 'Python',
    framework: 'python-telegram-bot',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Inline keyboards', 'Webhooks', 'Payment integration', 'Multi-language'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'slack-bot-node',
    name: 'Slack Bot Node.js',
    description: 'Slack workspace bot with interactive messages and workflows',
    icon: 'Hash',
    category: 'bot',
    tags: ['slack', 'bot', 'nodejs', 'automation', 'workspace'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Bolt',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Interactive messages', 'Workflows', 'Slash commands', 'Event handling'],
    files: {},
    dependencies: { '@slack/bolt': '^3.0.0' },
    uses: 1890,
    stars: 134,
    forks: 35,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Blockchain & Web3
  {
    slug: 'ethereum-dapp',
    name: 'Ethereum DApp Starter',
    description: 'Decentralized app with Solidity smart contracts and React frontend',
    icon: 'Coins',
    category: 'web3',
    tags: ['ethereum', 'solidity', 'web3', 'blockchain', 'dapp'],
    authorName: 'Web3 Builders',
    authorVerified: true,
    language: 'Solidity',
    framework: 'Hardhat',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['Smart contracts', 'Web3 integration', 'MetaMask', 'Testing suite'],
    files: {},
    dependencies: {},
    uses: 2120,
    stars: 156,
    forks: 40,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nft-marketplace',
    name: 'NFT Marketplace',
    description: 'Full-stack NFT marketplace with minting, buying, and selling',
    icon: 'Image',
    category: 'web3',
    tags: ['nft', 'ethereum', 'marketplace', 'web3', 'ipfs'],
    authorName: 'NFT Pro',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Next.js',
    difficulty: 'advanced' as const,
    estimatedTime: '6 minutes',
    features: ['NFT minting', 'IPFS storage', 'Marketplace', 'Wallet integration'],
    files: {},
    dependencies: {},
    uses: 1780,
    stars: 123,
    forks: 31,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // DevOps & Tools
  {
    slug: 'github-actions-ci',
    name: 'GitHub Actions CI/CD',
    description: 'Complete CI/CD pipeline with GitHub Actions, testing, and deployment',
    icon: 'GitPullRequest',
    category: 'tools',
    tags: ['github-actions', 'ci-cd', 'devops', 'automation'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'YAML',
    framework: 'GitHub Actions',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Automated testing', 'Multi-environment deploy', 'Docker builds', 'Secrets management'],
    files: {},
    dependencies: {},
    uses: 2890,
    stars: 198,
    forks: 52,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'docker-compose-stack',
    name: 'Docker Compose Stack',
    description: 'Multi-container Docker application with database, cache, and monitoring',
    icon: 'Container',
    category: 'tools',
    tags: ['docker', 'docker-compose', 'devops', 'containers'],
    authorName: 'DevOps Masters',
    authorVerified: true,
    language: 'YAML',
    framework: 'Docker',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Multi-container', 'Database setup', 'Redis cache', 'Monitoring stack'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 167,
    forks: 43,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Starter Templates
  {
    slug: 'html-css-js',
    name: 'HTML/CSS/JS Starter',
    description: 'Simple web page with HTML5, CSS3, and vanilla JavaScript',
    icon: 'Code',
    category: 'starter',
    tags: ['html', 'css', 'javascript', 'beginner', 'web'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'HTML',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Responsive design', 'Modern CSS', 'JavaScript interactivity', 'SEO friendly'],
    files: {},
    dependencies: {},
    uses: 8920,
    stars: 456,
    forks: 123,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'python-script',
    name: 'Python Script Starter',
    description: 'Python script template with common utilities and best practices',
    icon: 'FileCode',
    category: 'starter',
    tags: ['python', 'script', 'automation', 'beginner'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Argument parsing', 'Logging setup', 'Error handling', 'Type hints'],
    files: {},
    dependencies: {},
    uses: 6780,
    stars: 342,
    forks: 89,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'nodejs-cli',
    name: 'Node.js CLI Tool',
    description: 'Command-line tool with Node.js, Commander.js, and chalk',
    icon: 'Terminal',
    category: 'starter',
    tags: ['nodejs', 'cli', 'terminal', 'tool'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: undefined,
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Command parsing', 'Colorful output', 'Progress bars', 'Config files'],
    files: {},
    dependencies: { 'commander': '^11.0.0', 'chalk': '^5.0.0' },
    uses: 4320,
    stars: 234,
    forks: 61,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // AI/ML Templates
  {
    slug: 'openai-chatbot',
    name: 'OpenAI Chatbot',
    description: 'AI chatbot powered by OpenAI GPT-4 with streaming responses',
    icon: 'Bot',
    category: 'ai',
    tags: ['openai', 'gpt4', 'chatbot', 'ai', 'typescript'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Express',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['GPT-4 integration', 'Streaming responses', 'Chat history', 'TypeScript'],
    files: {},
    dependencies: { 'openai': '^4.0.0', 'express': '^4.0.0' },
    uses: 8920,
    stars: 567,
    forks: 234,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'langchain-rag',
    name: 'LangChain RAG App',
    description: 'Retrieval-Augmented Generation with LangChain and vector databases',
    icon: 'Brain',
    category: 'ai',
    tags: ['langchain', 'rag', 'vectordb', 'ai', 'python'],
    authorName: 'AI Masters',
    authorVerified: true,
    language: 'Python',
    framework: 'FastAPI',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Vector search', 'Document processing', 'RAG pipeline', 'FastAPI'],
    files: {},
    dependencies: {},
    uses: 4560,
    stars: 342,
    forks: 123,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'huggingface-transformers',
    name: 'Hugging Face Model',
    description: 'Deploy Hugging Face transformers with Gradio interface',
    icon: 'Sparkles',
    category: 'ai',
    tags: ['huggingface', 'transformers', 'gradio', 'nlp', 'python'],
    authorName: 'ML Engineers',
    authorVerified: true,
    language: 'Python',
    framework: 'Gradio',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Pre-trained models', 'Gradio UI', 'Easy deployment', 'Multiple models'],
    files: {},
    dependencies: {},
    uses: 3890,
    stars: 289,
    forks: 98,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'stable-diffusion-api',
    name: 'Stable Diffusion API',
    description: 'Image generation API with Stable Diffusion and custom models',
    icon: 'Image',
    category: 'ai',
    tags: ['stable-diffusion', 'image-generation', 'ai', 'api', 'python'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: 'FastAPI',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Image generation', 'Custom models', 'API endpoints', 'Queue system'],
    files: {},
    dependencies: {},
    uses: 5670,
    stars: 423,
    forks: 167,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'tensorflow-mnist',
    name: 'TensorFlow MNIST',
    description: 'Train and deploy a neural network for digit recognition',
    icon: 'Cpu',
    category: 'ai',
    tags: ['tensorflow', 'mnist', 'neural-network', 'ml', 'python'],
    authorName: 'ML Basics',
    authorVerified: true,
    language: 'Python',
    framework: 'TensorFlow',
    difficulty: 'beginner' as const,
    estimatedTime: '2 minutes',
    features: ['Neural network', 'MNIST dataset', 'Model training', 'Web interface'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 167,
    forks: 56,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'pytorch-classifier',
    name: 'PyTorch Image Classifier',
    description: 'Image classification with PyTorch and pre-trained models',
    icon: 'Camera',
    category: 'ai',
    tags: ['pytorch', 'classification', 'computer-vision', 'ml', 'python'],
    authorName: 'PyTorch Pro',
    authorVerified: true,
    language: 'Python',
    framework: 'PyTorch',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Pre-trained models', 'Image upload', 'Real-time inference', 'REST API'],
    files: {},
    dependencies: {},
    uses: 3120,
    stars: 234,
    forks: 89,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'whisper-transcription',
    name: 'Whisper Transcription',
    description: 'Audio transcription service using OpenAI Whisper',
    icon: 'Mic',
    category: 'ai',
    tags: ['whisper', 'transcription', 'audio', 'ai', 'python'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: 'Flask',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Audio transcription', 'Multiple languages', 'File upload', 'REST API'],
    files: {},
    dependencies: {},
    uses: 4230,
    stars: 312,
    forks: 123,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Data Science Templates
  {
    slug: 'jupyter-notebook',
    name: 'Jupyter Notebook',
    description: 'Interactive data science notebook with Python kernel',
    icon: 'BookOpen',
    category: 'data',
    tags: ['jupyter', 'notebook', 'data-science', 'python', 'analysis'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Python',
    framework: 'Jupyter',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Interactive notebooks', 'Data visualization', 'Python kernel', 'Markdown'],
    files: {},
    dependencies: {},
    uses: 7890,
    stars: 456,
    forks: 178,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'pandas-analysis',
    name: 'Pandas Data Analysis',
    description: 'Data analysis dashboard with Pandas and Plotly',
    icon: 'BarChart',
    category: 'data',
    tags: ['pandas', 'plotly', 'data-analysis', 'python', 'dashboard'],
    authorName: 'Data Scientists',
    authorVerified: true,
    language: 'Python',
    framework: 'Streamlit',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Data analysis', 'Interactive charts', 'CSV upload', 'Dashboard'],
    files: {},
    dependencies: {},
    uses: 5670,
    stars: 342,
    forks: 134,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'r-shiny-dashboard',
    name: 'R Shiny Dashboard',
    description: 'Interactive data dashboard with R and Shiny',
    icon: 'LineChart',
    category: 'data',
    tags: ['r', 'shiny', 'dashboard', 'data-viz', 'statistics'],
    authorName: 'R Masters',
    authorVerified: true,
    language: 'R',
    framework: 'Shiny',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Interactive UI', 'Statistical analysis', 'Real-time updates', 'Data viz'],
    files: {},
    dependencies: {},
    uses: 3450,
    stars: 234,
    forks: 89,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'scikit-learn-ml',
    name: 'Scikit-learn ML Pipeline',
    description: 'Machine learning pipeline with scikit-learn and model deployment',
    icon: 'GitBranch',
    category: 'data',
    tags: ['scikit-learn', 'machine-learning', 'pipeline', 'python', 'ml'],
    authorName: 'ML Engineers',
    authorVerified: true,
    language: 'Python',
    framework: 'Flask',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['ML pipeline', 'Model training', 'API deployment', 'Data preprocessing'],
    files: {},
    dependencies: {},
    uses: 4120,
    stars: 289,
    forks: 112,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Games Templates
  {
    slug: 'phaser-platformer',
    name: 'Phaser Platformer',
    description: '2D platformer game with Phaser 3 and TypeScript',
    icon: 'Gamepad2',
    category: 'games',
    tags: ['phaser', 'game', 'platformer', 'typescript', '2d'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Phaser',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Physics engine', 'Sprite animations', 'Level design', 'Sound effects'],
    files: {},
    dependencies: { 'phaser': '^3.0.0' },
    uses: 4560,
    stars: 312,
    forks: 134,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'kaboom-js',
    name: 'Kaboom.js Game',
    description: 'Simple and fun game development with Kaboom.js',
    icon: 'Zap',
    category: 'games',
    tags: ['kaboom', 'game', 'javascript', 'simple', 'fun'],
    authorName: 'Game Devs',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Kaboom',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Simple API', 'Built-in sprites', 'Quick prototyping', 'Fun'],
    files: {},
    dependencies: { 'kaboom': '^3000.0.0' },
    uses: 6780,
    stars: 423,
    forks: 189,
    isFeatured: true,
    isOfficial: false,
    published: true
  },
  {
    slug: 'three-js-3d',
    name: 'Three.js 3D Scene',
    description: '3D graphics and animations with Three.js',
    icon: 'Box',
    category: 'games',
    tags: ['threejs', '3d', 'webgl', 'graphics', 'animation'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Three.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['3D graphics', 'Animations', 'Lighting', 'Camera controls'],
    files: {},
    dependencies: { 'three': '^0.160.0' },
    uses: 3890,
    stars: 289,
    forks: 98,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'p5js-creative',
    name: 'p5.js Creative Coding',
    description: 'Creative coding and generative art with p5.js',
    icon: 'Palette',
    category: 'games',
    tags: ['p5js', 'creative-coding', 'art', 'generative', 'canvas'],
    authorName: 'Creative Coders',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'p5.js',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Canvas drawing', 'Animation', 'Interactivity', 'Creative tools'],
    files: {},
    dependencies: { 'p5': '^1.0.0' },
    uses: 5230,
    stars: 367,
    forks: 145,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'unity-webgl',
    name: 'Unity WebGL Export',
    description: 'Unity game exported to WebGL for browser play',
    icon: 'Play',
    category: 'games',
    tags: ['unity', 'webgl', '3d', 'game', 'export'],
    authorName: 'Unity Devs',
    authorVerified: true,
    language: 'C#',
    framework: 'Unity',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['Unity engine', 'WebGL export', '3D graphics', 'Browser compatible'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 178,
    forks: 67,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // DevOps Templates
  {
    slug: 'docker-compose',
    name: 'Docker Compose Stack',
    description: 'Multi-container application with Docker Compose',
    icon: 'Container',
    category: 'devops',
    tags: ['docker', 'compose', 'containers', 'devops', 'microservices'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'YAML',
    framework: 'Docker',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Multi-container', 'Service orchestration', 'Networking', 'Volumes'],
    files: {},
    dependencies: {},
    uses: 4230,
    stars: 312,
    forks: 123,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'kubernetes-deployment',
    name: 'Kubernetes Deployment',
    description: 'Deploy applications to Kubernetes with manifests',
    icon: 'Cloud',
    category: 'devops',
    tags: ['kubernetes', 'k8s', 'deployment', 'devops', 'cloud'],
    authorName: 'Cloud Experts',
    authorVerified: true,
    language: 'YAML',
    framework: 'Kubernetes',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['K8s manifests', 'Service deployment', 'Ingress', 'ConfigMaps'],
    files: {},
    dependencies: {},
    uses: 3120,
    stars: 234,
    forks: 89,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'github-actions',
    name: 'GitHub Actions CI/CD',
    description: 'Automated CI/CD pipeline with GitHub Actions',
    icon: 'GitBranch',
    category: 'devops',
    tags: ['github-actions', 'cicd', 'automation', 'devops', 'yaml'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'YAML',
    framework: 'GitHub Actions',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['CI/CD pipeline', 'Automated testing', 'Deployment', 'Workflows'],
    files: {},
    dependencies: {},
    uses: 5890,
    stars: 423,
    forks: 167,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'terraform-aws',
    name: 'Terraform AWS',
    description: 'Infrastructure as Code for AWS with Terraform',
    icon: 'Server',
    category: 'devops',
    tags: ['terraform', 'aws', 'iac', 'infrastructure', 'cloud'],
    authorName: 'DevOps Pro',
    authorVerified: true,
    language: 'HCL',
    framework: 'Terraform',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Infrastructure as Code', 'AWS resources', 'State management', 'Modules'],
    files: {},
    dependencies: {},
    uses: 2780,
    stars: 198,
    forks: 76,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Blockchain Templates
  {
    slug: 'ethereum-dapp',
    name: 'Ethereum DApp',
    description: 'Decentralized application with Solidity and Web3.js',
    icon: 'Coins',
    category: 'blockchain',
    tags: ['ethereum', 'solidity', 'web3', 'dapp', 'blockchain'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'Solidity',
    framework: 'Hardhat',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Smart contracts', 'Web3 integration', 'MetaMask', 'Testing'],
    files: {},
    dependencies: {},
    uses: 3450,
    stars: 267,
    forks: 112,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'solana-program',
    name: 'Solana Program',
    description: 'On-chain program for Solana blockchain with Anchor',
    icon: 'Zap',
    category: 'blockchain',
    tags: ['solana', 'anchor', 'rust', 'blockchain', 'web3'],
    authorName: 'Solana Devs',
    authorVerified: true,
    language: 'Rust',
    framework: 'Anchor',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['Anchor framework', 'On-chain programs', 'Client SDK', 'Testing'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 189,
    forks: 78,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'nft-marketplace',
    name: 'NFT Marketplace',
    description: 'Full-stack NFT marketplace with minting and trading',
    icon: 'Image',
    category: 'blockchain',
    tags: ['nft', 'marketplace', 'ethereum', 'ipfs', 'web3'],
    authorName: 'NFT Masters',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Next.js',
    difficulty: 'advanced' as const,
    estimatedTime: '5 minutes',
    features: ['NFT minting', 'IPFS storage', 'Trading', 'Wallet connect'],
    files: {},
    dependencies: {},
    uses: 4120,
    stars: 312,
    forks: 134,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Bot Templates
  {
    slug: 'discord-bot',
    name: 'Discord Bot',
    description: 'Feature-rich Discord bot with slash commands',
    icon: 'MessageSquare',
    category: 'bots',
    tags: ['discord', 'bot', 'typescript', 'discord.js', 'slash-commands'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Discord.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Slash commands', 'Event handling', 'Permissions', 'Database'],
    files: {},
    dependencies: { 'discord.js': '^14.0.0' },
    uses: 6780,
    stars: 456,
    forks: 189,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'telegram-bot',
    name: 'Telegram Bot',
    description: 'Telegram bot with inline keyboards and webhooks',
    icon: 'Send',
    category: 'bots',
    tags: ['telegram', 'bot', 'python', 'aiogram', 'webhooks'],
    authorName: 'Bot Builders',
    authorVerified: true,
    language: 'Python',
    framework: 'aiogram',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Inline keyboards', 'Webhooks', 'Commands', 'Media handling'],
    files: {},
    dependencies: {},
    uses: 4560,
    stars: 342,
    forks: 134,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'slack-app',
    name: 'Slack App',
    description: 'Slack workspace app with slash commands and interactivity',
    icon: 'Hash',
    category: 'bots',
    tags: ['slack', 'bot', 'app', 'nodejs', 'bolt'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Bolt',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Slash commands', 'Interactive messages', 'Events API', 'OAuth'],
    files: {},
    dependencies: { '@slack/bolt': '^3.0.0' },
    uses: 3890,
    stars: 289,
    forks: 112,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'whatsapp-bot',
    name: 'WhatsApp Bot',
    description: 'WhatsApp bot with automated responses and media',
    icon: 'MessageCircle',
    category: 'bots',
    tags: ['whatsapp', 'bot', 'nodejs', 'automation', 'messaging'],
    authorName: 'Messaging Pro',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Baileys',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Auto responses', 'Media messages', 'Groups', 'QR authentication'],
    files: {},
    dependencies: {},
    uses: 5230,
    stars: 389,
    forks: 156,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // Tools & Utilities
  {
    slug: 'url-shortener',
    name: 'URL Shortener',
    description: 'URL shortening service with analytics and custom aliases',
    icon: 'Link',
    category: 'tools',
    tags: ['url-shortener', 'analytics', 'nodejs', 'mongodb', 'api'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Express',
    difficulty: 'beginner' as const,
    estimatedTime: '2 minutes',
    features: ['Short URLs', 'Analytics', 'Custom aliases', 'QR codes'],
    files: {},
    dependencies: { 'express': '^4.0.0', 'mongoose': '^7.0.0' },
    uses: 7890,
    stars: 523,
    forks: 234,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'markdown-editor',
    name: 'Markdown Editor',
    description: 'Live markdown editor with preview and export options',
    icon: 'FileText',
    category: 'tools',
    tags: ['markdown', 'editor', 'react', 'preview', 'export'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'React',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Live preview', 'Syntax highlighting', 'Export options', 'Themes'],
    files: {},
    dependencies: { 'react': '^18.0.0', 'marked': '^11.0.0' },
    uses: 5670,
    stars: 412,
    forks: 167,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Secure password generator with customizable options',
    icon: 'Key',
    category: 'tools',
    tags: ['password', 'security', 'generator', 'javascript', 'tool'],
    authorName: 'Security Tools',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Vanilla JS',
    difficulty: 'beginner' as const,
    estimatedTime: '30 seconds',
    features: ['Customizable length', 'Character options', 'Strength meter', 'Copy button'],
    files: {},
    dependencies: {},
    uses: 8920,
    stars: 612,
    forks: 289,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes for URLs, text, WiFi, and more',
    icon: 'QrCode',
    category: 'tools',
    tags: ['qr-code', 'generator', 'javascript', 'tool', 'utility'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'React',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Multiple formats', 'Customization', 'Download options', 'Bulk generation'],
    files: {},
    dependencies: { 'qrcode': '^1.5.0', 'react': '^18.0.0' },
    uses: 6340,
    stars: 489,
    forks: 198,
    isFeatured: false,
    isOfficial: true,
    published: true
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON with syntax highlighting',
    icon: 'Braces',
    category: 'tools',
    tags: ['json', 'formatter', 'validator', 'tool', 'javascript'],
    authorName: 'Dev Tools',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Vue.js',
    difficulty: 'beginner' as const,
    estimatedTime: '1 minute',
    features: ['Format/Minify', 'Validation', 'Syntax highlighting', 'Tree view'],
    files: {},
    dependencies: { 'vue': '^3.0.0' },
    uses: 7230,
    stars: 534,
    forks: 223,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes for design projects',
    icon: 'Palette',
    category: 'tools',
    tags: ['color', 'palette', 'design', 'generator', 'css'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Next.js',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Color schemes', 'Export formats', 'Accessibility check', 'Save palettes'],
    files: {},
    dependencies: { 'next': '^14.0.0', 'chroma-js': '^2.0.0' },
    uses: 4890,
    stars: 378,
    forks: 145,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // Additional Backend Templates
  {
    slug: 'go-fiber-api',
    name: 'Go Fiber API',
    description: 'High-performance REST API with Go and Fiber framework',
    icon: 'Zap',
    category: 'api',
    tags: ['go', 'fiber', 'api', 'rest', 'performance'],
    authorName: 'Go Masters',
    authorVerified: true,
    language: 'Go',
    framework: 'Fiber',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Fast performance', 'Middleware', 'JWT auth', 'PostgreSQL'],
    files: {},
    dependencies: {},
    uses: 3670,
    stars: 278,
    forks: 98,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'rust-actix-web',
    name: 'Rust Actix Web',
    description: 'Blazing fast web service with Rust and Actix',
    icon: 'Server',
    category: 'api',
    tags: ['rust', 'actix', 'web', 'api', 'performance'],
    authorName: 'Rust Pro',
    authorVerified: true,
    language: 'Rust',
    framework: 'Actix',
    difficulty: 'advanced' as const,
    estimatedTime: '3 minutes',
    features: ['Type safety', 'Async/await', 'WebSockets', 'Database pool'],
    files: {},
    dependencies: {},
    uses: 2890,
    stars: 234,
    forks: 78,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'deno-fresh',
    name: 'Deno Fresh',
    description: 'Modern full-stack framework for Deno with islands architecture',
    icon: 'Layers',
    category: 'web',
    tags: ['deno', 'fresh', 'islands', 'typescript', 'fullstack'],
    authorName: 'Deno Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Fresh',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Islands architecture', 'Zero JS by default', 'TypeScript', 'Fast'],
    files: {},
    dependencies: {},
    uses: 2340,
    stars: 189,
    forks: 67,
    isFeatured: false,
    isOfficial: false,
    published: true
  },
  {
    slug: 'bun-elysia',
    name: 'Bun + Elysia',
    description: 'Ultra-fast API with Bun runtime and Elysia framework',
    icon: 'Zap',
    category: 'api',
    tags: ['bun', 'elysia', 'api', 'typescript', 'fast'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Elysia',
    difficulty: 'intermediate' as const,
    estimatedTime: '2 minutes',
    features: ['Bun runtime', 'Type safety', 'Swagger docs', 'WebSockets'],
    files: {},
    dependencies: {},
    uses: 3120,
    stars: 267,
    forks: 89,
    isFeatured: false,
    isOfficial: true,
    published: true
  },

  // CMS Templates
  {
    slug: 'strapi-cms',
    name: 'Strapi Headless CMS',
    description: 'Customizable headless CMS with REST and GraphQL APIs',
    icon: 'Database',
    category: 'cms',
    tags: ['strapi', 'cms', 'headless', 'api', 'content'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Strapi',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Content types', 'Media library', 'REST/GraphQL', 'Admin panel'],
    files: {},
    dependencies: {},
    uses: 4560,
    stars: 342,
    forks: 123,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'directus-backend',
    name: 'Directus Data Platform',
    description: 'Open data platform with instant REST and GraphQL APIs',
    icon: 'Grid',
    category: 'cms',
    tags: ['directus', 'cms', 'database', 'api', 'platform'],
    authorName: 'Data Platform',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Directus',
    difficulty: 'intermediate' as const,
    estimatedTime: '3 minutes',
    features: ['Database wrapper', 'Real-time', 'Webhooks', 'Asset transformation'],
    files: {},
    dependencies: {},
    uses: 3230,
    stars: 256,
    forks: 98,
    isFeatured: false,
    isOfficial: false,
    published: true
  },

  // E-commerce Templates
  {
    slug: 'shopify-app',
    name: 'Shopify App',
    description: 'Custom Shopify app with Admin API and storefront integration',
    icon: 'ShoppingCart',
    category: 'ecommerce',
    tags: ['shopify', 'ecommerce', 'app', 'nodejs', 'react'],
    authorName: 'E-Code Team',
    authorVerified: true,
    language: 'JavaScript',
    framework: 'Express',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Admin API', 'Webhooks', 'App Bridge', 'Billing API'],
    files: {},
    dependencies: {},
    uses: 3890,
    stars: 289,
    forks: 112,
    isFeatured: true,
    isOfficial: true,
    published: true
  },
  {
    slug: 'medusa-store',
    name: 'Medusa E-commerce',
    description: 'Headless commerce engine with Medusa.js',
    icon: 'Store',
    category: 'ecommerce',
    tags: ['medusa', 'ecommerce', 'headless', 'api', 'store'],
    authorName: 'Commerce Pro',
    authorVerified: true,
    language: 'TypeScript',
    framework: 'Medusa',
    difficulty: 'advanced' as const,
    estimatedTime: '4 minutes',
    features: ['Multi-currency', 'Inventory', 'Cart API', 'Admin dashboard'],
    files: {},
    dependencies: {},
    uses: 2670,
    stars: 212,
    forks: 87,
    isFeatured: false,
    isOfficial: false,
    published: true
  }
];

async function seedTemplates() {
  try {
    // Clear existing templates first to start fresh
    await db.delete(templates);
    
    // Insert all templates with duplicate handling
    let successCount = 0;
    let failCount = 0;
    
    for (const template of REPLIT_TEMPLATES) {
      try {
        await db.insert(templates).values(template);
        successCount++;
      } catch (error: any) {
        if (error.code === '23505') {
          // Template already exists
        } else {
          logger.error(`❌ Failed to add template ${template.name}:`, error.message);
          failCount++;
        }
      }
    }
  } catch (error) {
    logger.error('❌ Error seeding templates:', error);
    throw error;
  }
}

// Run the seed function
seedTemplates()
  .then(() => {
    process.exit(0);
  })
  .catch((error) => {
    logger.error('❌ Template seeding failed:', error);
    process.exit(1);
  });